WITH SECOND AS
(
    SELECT C.ID
    FROM ECOLI_DATA AS C
        JOIN ECOLI_DATA AS P
        ON C.PARENT_ID = P.ID
    WHERE P.PARENT_ID IS NULL
)

SELECT T.ID
FROM ECOLI_DATA AS T
    JOIN SECOND
    ON T.PARENT_ID = SECOND.ID
ORDER BY T.ID