SELECT E.ID, IFNULL(CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS E
    LEFT OUTER JOIN (
        SELECT COUNT(*) AS CHILD_COUNT
            , PARENT_ID
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NOT NULL
        GROUP BY PARENT_ID
    ) AS D
    ON E.ID = D.PARENT_ID
ORDER BY E.ID
