# # SELECT COUNT(*) AS FISH_COUNT
# #     , FISH_NAME
# SELECT *
# FROM FISH_INFO I
#     JOIN FISH_NAME_INFO N USING(FISH_TYPE)
# GROUP BY FISH_TYPE
# # ORDER BY FISH_COUNT DESC

WITH B AS (
    SELECT FISH_TYPE, COUNT(*) AS FISH_COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE)

SELECT FISH_COUNT
    , FISH_NAME
FROM FISH_NAME_INFO A
    RIGHT JOIN B
    ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY FISH_COUNT DESC