-- 코드를 입력하세요
SELECT  J.FLAVOR 
FROM
(SELECT FLAVOR, SUM(TOTAL_ORDER) AS SJ
FROM JULY J
GROUP BY FLAVOR) AS J, 
(SELECT FLAVOR, SUM(TOTAL_ORDER) AS SF
FROM FIRST_HALF F
GROUP BY FLAVOR) AS F
WHERE J.FLAVOR = F.FLAVOR
GROUP BY J.FLAVOR
ORDER BY SUM(SJ + SF) DESC
LIMIT 3