# -- 코드를 입력하세요
WITH RECURSIVE RT AS (
    SELECT 0 AS N
    UNION ALL
    SELECT N + 1 
    FROM RT
    WHERE N < 23
)

SELECT RT.N, COUNT(ANIMAL_ID) AS COUNT
FROM RT LEFT OUTER JOIN ANIMAL_oUTS AS A ON RT.N = HOUR(A.DATETIME)
GROUP BY RT.N
ORDER BY RT.N
