SELECT
    ED.ID AS ID
    , ED.GENOTYPE AS GENOTYPE
    , PED.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA ED
    INNER JOIN ECOLI_DATA PED
    ON ED.PARENT_ID = PED.ID
WHERE (ED.GENOTYPE & PED.GENOTYPE) = PED.GENOTYPE
ORDER BY ED.ID