SELECT I.ID, N.FISH_NAME, LENGTH
FROM FISH_INFO I
    JOIN FISH_NAME_INFO N USING (FISH_TYPE)
WHERE (LENGTH, FISH_TYPE) IN
(SELECT MAX(LENGTH) AS MAX_LEN, FISH_TYPE 
FROM FISH_INFO I
GROUP BY FISH_TYPE
)
ORDER BY I.ID ASC